- name: BSD PHP hardening
  hosts: bsd
  gather_facts: no
  vars_files:
    - vars/management.yml
  environment:
    PATH: "{{ ansible_task_path }}"
  pre_tasks:
    - name: Validate host_files is defined
      assert:
        that:
          - host_files is defined
        fail_msg: >
          Missing required variable: host_files.
          Make sure vars/management.yml is populated.
      run_once: true
  roles:
    - {role: service_bsd_php_harden, ignore_errors: yes}
