- name: Windows Backup
  hosts: windows
  gather_facts: no
  vars_files:
    - vars/management.yml
  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - windows_temp_dir is defined
          - host_files is defined
        fail_msg: >
          Missing required variables. Make sure vars/management.yml is populated.
          Required: windows_temp_dir, host_files
      ignore_errors: no
      run_once: true
  roles:
    - {role: windows_backup, ignore_errors: yes}
